### ISSUE TITLE
Código de retorno inadequado.

### ISSUE THREAD

**Issue by ronaiza-cardoso** [cubonetwork/fullstack-challenge#1]
Sei que `desing` de api as vezes pode ser algo muito complicado e discussões sobre qual `status code` retornar se tornam verdadeiras guerras, porém uma coisa que acho ser consenso entre os desenvolvedores de api é o `status code` que se deve retornar em caso de post com dados incorretos ou não formatados como a `api` espera ser diferente de 500. Fiz uma pesquisa no grupo [Node.js Brasil](https://t.me/NodejsBR) que conta com mais de 1k de membros e a resposta que o @FelipeMonobe deu resume bem o que penso: 
![image](https://user-images.githubusercontent.com/7999914/27008325-38330798-4e45-11e7-94d1-e68d2cbef3b0.png)

ele sugeriu o uso do `status code` 400 estou mais inclinada a retornar 200, o `default` do mongodf é 200.

> Obs 3.: Considere validar os campos também na API e em caso de inconsistência retornar erro num JSON estruturado com código HTTP 500`

**Comment by FelipeMonobe** [comment]
Concordo parcialmente.
Pra reiterar parte do que eu disse, na verdade, erros 400 podem ser mais culpa do desenvolvedor que do usuário, pois devemos evitar ao máximo o front-end de possibilitar o envio de dados mal formatados ou faltosos para o back-end. Se mesmo com validações no HTML/Javascript isso acontecer (usuário alterou/interceptou externamente) , então talvez seja válido dizer que a culpa é dele.
Enfim, o back-end deve estar preparado para lidar com vários tipos de `status codes` diferentes, por exemplo:
- Se por meio de validações, for percebido um problema de **inconsistência vindo no corpo da requisição**, então é certo retornar `status 400`;
- Se após ou mesmo durante as validações ocorrer um **erro de processamento** que não é causado por inconsistências no corpo da requisição, retorne `status 500`;
- Se todas as operações são executadas **sem disparo de exceções**, retorne `status 200`, mesmo que tenha um resultado vazio de banco (deu certo, só não teve resultados para aquela query);
Portanto, idealmente os endpoints de uma API não devem estar preparados para retornar um status ou outro, apenas. E sim uma gama deles, de acordo com o que realmente aconteceu. Pois estes servem para ajudar o desenvolvedor da outra ponta (nesse a mesma pessoa) ter uma ideia melhor do que pode ter ocorrido.

**Comment by danilodevhub** [comment]
Olá @yesroh e @FelipeMonobe realmente esta é uma questão filosófica, já vi algumas APIs que considero referência retornando status code 500 pra estes casos (Ex.: GraphAPI do Facebook).
Mas concordo com vocês, status code 400 pra este caso é mais apropriado, já atualizei o README :slightly_smiling_face:

Outra referência legal sobre status code: http://www.restpatterns.org/HTTP_Status_Codes
