### ISSUE TITLE
Banco de Dados para a aplicação

### ISSUE THREAD

**Issue by vitorsilvalima** [cubonetwork/fullstack-challenge#2]
Boa tarde, 
Me parece que vocês utilizando um banco de dados relacional para desenvolver essa aplicação. Vocês têm alguma preferência quanto a qual banco utilizar?
Estou implementando o backend com persistência dos dados em MongoDB.

**Comment by felipefialho** [comment]
@danilodevhub

**Comment by vitorsilvalima** [comment]
Foi respondida por email:
"Nós usamos o DynamoDB da AWS, parecido com o Mongo em alguns aspectos. 
Pode utilizar o banco de sua preferência, se já começou com MongoDB siga com ele."

**Comment by danilodevhub** [comment]
Olá @vitorsilvalima boa tarde!
Aqui utilizamos o DynamoDB da AWS, parecido com Mongo em alguns aspectos.
Você pode utilizar o banco de sua preferência, se começou com MongoDB pode seguir com ele mesmo...
