### ISSUE TITLE
Dúvida no cadastro da participação

### ISSUE THREAD

**Issue by vitorsilvalima** [cubonetwork/fullstack-challenge#3]
Acho que já está meio tarde para fazer esta pergunta, mas eu preciso saber se a participação é entrada em porcentagem pelo usuário ou se  esta porcentagem é calculada no momento que eu chamo o endpoint /employees.

**Comment by danilodevhub** [comment]
olá @vitorsilvalima, nunca é tarde.. hehe
respondendo... a participação é entrada em porcentagem pelo usuário e claro com limite total de 100% somado todos os "employees"
